COUNTRIES = [
    {"name": "Afghanistan", "time_zone": "Asia/Kabul"},
    {"name": "Albania", "time_zone": "Europe/Tirane"},
    {"name": "Algeria", "time_zone": "Africa/Algiers"},
    {"name": "Andorra", "time_zone": "Europe/Andorra"},
    {"name": "Angola", "time_zone": "Africa/Luanda"},
    {"name": "Antigua and Barbuda", "time_zone": "America/Antigua"},
    {"name": "Argentina", "time_zone": "America/Argentina/Buenos_Aires"},
    {"name": "Armenia", "time_zone": "Asia/Yerevan"},
    {"name": "Australia", "time_zone": "Australia/Sydney"},
    {"name": "Austria", "time_zone": "Europe/Vienna"},
    {"name": "Azerbaijan", "time_zone": "Asia/Baku"},
    {"name": "Bahamas", "time_zone": "America/Nassau"},
    {"name": "Bahrain", "time_zone": "Asia/Bahrain"},
    {"name": "Bangladesh", "time_zone": "Asia/Dhaka"},
    {"name": "Barbados", "time_zone": "America/Barbados"},
    {"name": "Belarus", "time_zone": "Europe/Minsk"},
    {"name": "Belgium", "time_zone": "Europe/Brussels"},
    {"name": "Belize", "time_zone": "America/Belize"},
    {"name": "Benin", "time_zone": "Africa/Porto-Novo"},
    {"name": "Bhutan", "time_zone": "Asia/Thimphu"},
    {"name": "Bolivia", "time_zone": "America/La_Paz"},
    {"name": "Bosnia and Herzegovina", "time_zone": "Europe/Sarajevo"},
    {"name": "Botswana", "time_zone": "Africa/Gaborone"},
    {"name": "Brazil", "time_zone": "America/Sao_Paulo"},
    {"name": "Brunei", "time_zone": "Asia/Brunei"},
    {"name": "Bulgaria", "time_zone": "Europe/Sofia"},
    {"name": "Burkina Faso", "time_zone": "Africa/Ouagadougou"},
    {"name": "Burundi", "time_zone": "Africa/Bujumbura"},
    {"name": "Canada", "time_zone": "America/Toronto"},
    {"name": "Chile", "time_zone": "America/Santiago"},
    {"name": "China", "time_zone": "Asia/Shanghai"},
    {"name": "Colombia", "time_zone": "America/Bogota"},
    {"name": "Croatia", "time_zone": "Europe/Zagreb"},
    {"name": "Cuba", "time_zone": "America/Havana"},
    {"name": "Cyprus", "time_zone": "Asia/Nicosia"},
    {"name": "Czech Republic", "time_zone": "Europe/Prague"},
    {"name": "Denmark", "time_zone": "Europe/Copenhagen"},
    {"name": "Djibouti", "time_zone": "Africa/Djibouti"},
    {"name": "Dominica", "time_zone": "America/Dominica"},
    {"name": "Dominican Republic", "time_zone": "America/Santo_Domingo"},
    {"name": "Ecuador", "time_zone": "America/Guayaquil"},
    {"name": "Egypt", "time_zone": "Africa/Cairo"},
    {"name": "El Salvador", "time_zone": "America/El_Salvador"},
    {"name": "Estonia", "time_zone": "Europe/Tallinn"},
    {"name": "Ethiopia", "time_zone": "Africa/Addis_Ababa"},
    {"name": "Fiji", "time_zone": "Pacific/Fiji"},
    {"name": "Finland", "time_zone": "Europe/Helsinki"},
    {"name": "France", "time_zone": "Europe/Paris"},
    {"name": "Gabon", "time_zone": "Africa/Libreville"},
    {"name": "Gambia", "time_zone": "Africa/Banjul"},
    {"name": "Georgia", "time_zone": "Asia/Tbilisi"},
    {"name": "Germany", "time_zone": "Europe/Berlin"},
    {"name": "Ghana", "time_zone": "Africa/Accra"},
    {"name": "Greece", "time_zone": "Europe/Athens"},
    {"name": "Grenada", "time_zone": "America/Grenada"},
    {"name": "Guatemala", "time_zone": "America/Guatemala"},
    {"name": "Guinea", "time_zone": "Africa/Conakry"},
    {"name": "Guinea-Bissau", "time_zone": "Africa/Bissau"},
    {"name": "Guyana", "time_zone": "America/Guyana"},
    {"name": "Haiti", "time_zone": "America/Port-au-Prince"},
    {"name": "Honduras", "time_zone": "America/Tegucigalpa"},
    {"name": "Hungary", "time_zone": "Europe/Budapest"},
    {"name": "Iceland", "time_zone": "Atlantic/Reykjavik"},
    {"name": "India", "time_zone": "Asia/Kolkata"},
    {"name": "Indonesia", "time_zone": "Asia/Jakarta"},
    {"name": "Iran", "time_zone": "Asia/Tehran"},
    {"name": "Iraq", "time_zone": "Asia/Baghdad"},
    {"name": "Ireland", "time_zone": "Europe/Dublin"},
    {"name": "Israel", "time_zone": "Asia/Jerusalem"},
    {"name": "Italy", "time_zone": "Europe/Rome"},
    {"name": "Jamaica", "time_zone": "America/Jamaica"},
    {"name": "Japan", "time_zone": "Asia/Tokyo"},
    {"name": "Jordan", "time_zone": "Asia/Amman"},
    {"name": "Kazakhstan", "time_zone": "Asia/Almaty"},
    {"name": "Kenya", "time_zone": "Africa/Nairobi"},
    {"name": "Kiribati", "time_zone": "Pacific/Tarawa"},
    {"name": "Kuwait", "time_zone": "Asia/Kuwait"},
    {"name": "Kyrgyzstan", "time_zone": "Asia/Bishkek"},
    {"name": "Laos", "time_zone": "Asia/Vientiane"},
    {"name": "Latvia", "time_zone": "Europe/Riga"},
    {"name": "Lebanon", "time_zone": "Asia/Beirut"},
    {"name": "Lesotho", "time_zone": "Africa/Maseru"},
    {"name": "Liberia", "time_zone": "Africa/Monrovia"},
    {"name": "Libya", "time_zone": "Africa/Tripoli"},
    {"name": "Liechtenstein", "time_zone": "Europe/Vaduz"},
    {"name": "Lithuania", "time_zone": "Europe/Vilnius"},
    {"name": "Luxembourg", "time_zone": "Europe/Luxembourg"},
    {"name": "Madagascar", "time_zone": "Indian/Antananarivo"},
    {"name": "Malawi", "time_zone": "Africa/Blantyre"},
    {"name": "Malaysia", "time_zone": "Asia/Kuala_Lumpur"},
    {"name": "Maldives", "time_zone": "Indian/Maldives"},
    {"name": "Mali", "time_zone": "Africa/Bamako"},
    {"name": "Malta", "time_zone": "Europe/Malta"},
    {"name": "Marshall Islands", "time_zone": "Pacific/Majuro"},
    {"name": "Mauritania", "time_zone": "Africa/Nouakchott"},
    {"name": "Mauritius", "time_zone": "Indian/Mauritius"},
    {"name": "Mexico", "time_zone": "America/Mexico_City"},
    {"name": "Micronesia", "time_zone": "Pacific/Pohnpei"},
    {"name": "Moldova", "time_zone": "Europe/Chisinau"},
    {"name": "Monaco", "time_zone": "Europe/Monaco"},
    {"name": "Mongolia", "time_zone": "Asia/Ulaanbaatar"},
    {"name": "Montenegro", "time_zone": "Europe/Podgorica"},
    {"name": "Morocco", "time_zone": "Africa/Casablanca"},
    {"name": "Mozambique", "time_zone": "Africa/Maputo"},
    {"name": "Myanmar (Burma)", "time_zone": "Asia/Yangon"},
    {"name": "Namibia", "time_zone": "Africa/Windhoek"},
    {"name": "Nauru", "time_zone": "Pacific/Nauru"},
    {"name": "Nepal", "time_zone": "Asia/Kathmandu"},
    {"name": "Netherlands", "time_zone": "Europe/Amsterdam"},
    {"name": "New Zealand", "time_zone": "Pacific/Auckland"},
    {"name": "Nicaragua", "time_zone": "America/Managua"},
    {"name": "Niger", "time_zone": "Africa/Niamey"},
    {"name": "Nigeria", "time_zone": "Africa/Lagos"},
    {"name": "North Korea", "time_zone": "Asia/Pyongyang"},
    {"name": "North Macedonia", "time_zone": "Europe/Skopje"},
    {"name": "Norway", "time_zone": "Europe/Oslo"},
    {"name": "Oman", "time_zone": "Asia/Muscat"},
    {"name": "Pakistan", "time_zone": "Asia/Karachi"},
    {"name": "Palau", "time_zone": "Pacific/Palau"},
    {"name": "Palestine", "time_zone": "Asia/Gaza"},
    {"name": "Panama", "time_zone": "America/Panama"},
    {"name": "Papua New Guinea", "time_zone": "Pacific/Port_Moresby"},
    {"name": "Paraguay", "time_zone": "America/Asuncion"},
    {"name": "Peru", "time_zone": "America/Lima"},
    {"name": "Philippines", "time_zone": "Asia/Manila"},
    {"name": "Poland", "time_zone": "Europe/Warsaw"},
    {"name": "Portugal", "time_zone": "Europe/Lisbon"},
    {"name": "Qatar", "time_zone": "Asia/Qatar"},
    {"name": "Romania", "time_zone": "Europe/Bucharest"},
    {"name": "Russia", "time_zone": "Europe/Moscow"},
    {"name": "Rwanda", "time_zone": "Africa/Kigali"},
    {"name": "Saint Kitts and Nevis", "time_zone": "America/St_Kitts"},
    {"name": "Saint Lucia", "time_zone": "America/St_Lucia"},
    {"name": "Saint Vincent and the Grenadines", "time_zone": "America/St_Vincent"},
    {"name": "Samoa", "time_zone": "Pacific/Apia"},
    {"name": "San Marino", "time_zone": "Europe/San_Marino"},
    {"name": "Saudi Arabia", "time_zone": "Asia/Riyadh"},
    {"name": "Senegal", "time_zone": "Africa/Dakar"},
    {"name": "Serbia", "time_zone": "Europe/Belgrade"},
    {"name": "Seychelles", "time_zone": "Indian/Mahe"},
    {"name": "Sierra Leone", "time_zone": "Africa/Freetown"},
    {"name": "Singapore", "time_zone": "Asia/Singapore"},
    {"name": "Slovakia", "time_zone": "Europe/Bratislava"},
    {"name": "Slovenia", "time_zone": "Europe/Ljubljana"},
    {"name": "Solomon Islands", "time_zone": "Pacific/Guadalcanal"},
    {"name": "Somalia", "time_zone": "Africa/Mogadishu"},
    {"name": "South Africa", "time_zone": "Africa/Johannesburg"},
    {"name": "South Korea", "time_zone": "Asia/Seoul"},
    {"name": "South Sudan", "time_zone": "Africa/Juba"},
    {"name": "Spain", "time_zone": "Europe/Madrid"},
    {"name": "Sri Lanka", "time_zone": "Asia/Colombo"},
    {"name": "Sudan", "time_zone": "Africa/Khartoum"},
    {"name": "Suriname", "time_zone": "America/Paramaribo"},
    {"name": "Sweden", "time_zone": "Europe/Stockholm"},
    {"name": "Switzerland", "time_zone": "Europe/Zurich"},
    {"name": "Syria", "time_zone": "Asia/Damascus"},
    {"name": "Taiwan", "time_zone": "Asia/Taipei"},
    {"name": "Tajikistan", "time_zone": "Asia/Dushanbe"},
    {"name": "Tanzania", "time_zone": "Africa/Dar_es_Salaam"},
    {"name": "Thailand", "time_zone": "Asia/Bangkok"},
    {"name": "Togo", "time_zone": "Africa/Lome"},
    {"name": "Tonga", "time_zone": "Pacific/Tongatapu"},
    {"name": "Trinidad and Tobago", "time_zone": "America/Port_of_Spain"},
    {"name": "Tunisia", "time_zone": "Africa/Tunis"},
    {"name": "Turkey", "time_zone": "Europe/Istanbul"},
    {"name": "Turkmenistan", "time_zone": "Asia/Ashgabat"},
    {"name": "Tuvalu", "time_zone": "Pacific/Funafuti"},
    {"name": "Uganda", "time_zone": "Africa/Kampala"},
    {"name": "Ukraine", "time_zone": "Europe/Kyiv"},
    {"name": "United Arab Emirates", "time_zone": "Asia/Dubai"},
    {"name": "United Kingdom", "time_zone": "Europe/London"},
    {"name": "United States", "time_zone": "America/New_York"},
    {"name": "Uruguay", "time_zone": "America/Montevideo"},
    {"name": "Uzbekistan", "time_zone": "Asia/Tashkent"},
    {"name": "Vanuatu", "time_zone": "Pacific/Efate"},
    {"name": "Vatican City", "time_zone": "Europe/Vatican"},
    {"name": "Venezuela", "time_zone": "America/Caracas"},
    {"name": "Vietnam", "time_zone": "Asia/Ho_Chi_Minh"},
    {"name": "United Kingdom", "time_zone": "Europe/London"},
    {"name": "Yemen", "time_zone": "Asia/Aden"},
    {"name": "Zambia", "time_zone": "Africa/Lusaka"},
    {"name": "Zimbabwe", "time_zone": "Africa/Harare"}
]
